package com.jbpm7.formmodellig;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String email;
	private java.lang.String complaint;
	private java.lang.Integer nationalId;

	public CustomerData() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getComplaint() {
		return this.complaint;
	}

	public void setComplaint(java.lang.String complaint) {
		this.complaint = complaint;
	}

	public java.lang.Integer getNationalId() {
		return this.nationalId;
	}

	public void setNationalId(java.lang.Integer nationalId) {
		this.nationalId = nationalId;
	}

	public CustomerData(java.lang.String name, java.lang.String email,
			java.lang.String complaint, java.lang.Integer nationalId) {
		this.name = name;
		this.email = email;
		this.complaint = complaint;
		this.nationalId = nationalId;
	}

}